import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import {
  ArrowUpRight,
  Check,
  ChevronRight,
  FileText,
  Layers,
  Lightbulb,
  Loader2,
  Search,
  Sparkle,
  Upload,
  Globe,
  Download,
  Info,
} from "lucide-react";
import {
  internalSources,
  externalSources,
  findings,
  opportunities,
  artifacts,
  workflowStages,
  type Opportunity,
} from "@/components/atlas/data/investigation";
import { OpportunityDrawer } from "@/components/atlas/OpportunityDrawer";

export const Route = createFileRoute("/overview")({
  validateSearch: (search: Record<string, unknown>) => ({
    company:
      typeof search["company"] === "string" && search["company"]
        ? (search["company"] as string)
        : "Linear",
  }),
  head: () => ({
    meta: [
      { title: "Investigation Overview — PM Atlas" },
      {
        name: "description",
        content:
          "Evidence sources, key findings, prioritized product opportunities, and an exportable strategy report from your PM Atlas investigation.",
      },
      { property: "og:title", content: "Investigation Overview — PM Atlas" },
      {
        property: "og:description",
        content: "Traceable, evidence-backed product strategy generated by PM Atlas.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Overview,
});

const stats = [
  { label: "Evidence sources", value: "17" },
  { label: "Customer reviews analysed", value: "934" },
  { label: "Competitors discovered", value: "7" },
  { label: "Opportunities identified", value: "17" },
];

const statusStyles: Record<string, string> = {
  Analysed: "border-positive/40 text-positive",
  Discovered: "border-positive/40 text-positive",
  Collecting: "border-border-strong text-muted-foreground",
  Uploaded: "border-positive/40 text-positive",
  "Not provided": "border-border text-muted-foreground",
};

function SectionHeading({
  eyebrow,
  icon: Icon,
  title,
  body,
  note,
}: {
  eyebrow: string;
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  body: string;
  note?: string;
}) {
  return (
    <div className="max-w-none">
      <p className="font-mono text-xs tracking-widest text-muted-foreground uppercase">{eyebrow}</p>
      <div className="mt-3 flex flex-wrap items-center gap-2.5">
        <Icon className="size-4 text-muted-foreground" />
        <h2 className="font-display text-xl font-semibold tracking-tight">{title}</h2>
        {note && (
          <span className="rounded-full border border-warning/40 px-2 py-0.5 font-mono text-[10px] tracking-wide text-muted-foreground uppercase">
            {note}
          </span>
        )}
      </div>
      <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
    </div>
  );
}



function Overview() {
  const { company } = Route.useSearch();
  const [selected, setSelected] = useState<Opportunity | null>(null);

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-40 border-b border-border bg-background/85 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-4">
          <Link to="/" className="font-display text-sm font-semibold tracking-tight">
            PM Atlas
          </Link>
          <Link
            to="/investigate"
            className="rounded-lg border border-border-strong px-3.5 py-2 text-sm font-medium transition-colors hover:bg-surface"
          >
            New investigation
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 pt-10 pb-24">
        <div className="rise">
          <nav aria-label="Breadcrumb">
            <ol className="flex flex-wrap items-center gap-2 text-xs">
              <li>
                <Link
                  to="/"
                  className="text-muted-foreground transition-colors hover:text-foreground"
                >
                  Atlas
                </Link>
              </li>
              <li aria-hidden className="text-border-strong">
                /
              </li>
              <li>
                <Link
                  to="/investigate"
                  className="text-muted-foreground transition-colors hover:text-foreground"
                >
                  Investigations
                </Link>
              </li>
              <li aria-hidden className="text-border-strong">
                /
              </li>
              <li aria-current="page" className="font-medium text-foreground">
                {company}
              </li>
            </ol>
          </nav>
          <div className="mt-3 flex flex-wrap items-center gap-3">
            <h1 className="font-display text-3xl font-semibold tracking-tight md:text-4xl">
              {company} — Investigation Overview
            </h1>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-positive/40 px-2.5 py-0.5 text-xs text-positive">
              <Check className="size-3.5" /> Complete
            </span>
          </div>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            PM Atlas synthesized internal and external evidence sources into key findings,
            prioritized product opportunities, and an exportable strategy report. Every
            recommendation traces back to the evidence behind it.
          </p>
          <div className="mt-5 flex items-start gap-2.5 rounded-xl border border-warning/40 bg-surface p-4">
            <Info className="mt-0.5 size-4 shrink-0 text-warning" />
            <p className="text-xs leading-relaxed text-muted-foreground">
              <span className="font-medium text-foreground">Demonstration data.</span> Counts,
              findings, opportunities, and report artifacts on this page are sample values shown to
              illustrate the workflow. They are not live investigation results — real evidence
              collection and generation arrive when the backend is connected.
            </p>
          </div>

        </div>


        {/* Workflow */}
        <ol className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {workflowStages.map((s, i) => (
            <li key={s.label} className="relative rounded-xl border border-border bg-card p-4">
              <div className="flex items-center gap-2">
                <span className="font-mono text-[10px] text-muted-foreground">
                  0{i + 1}
                </span>
                <p className="text-sm font-medium">{s.label}</p>
              </div>
              <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">{s.body}</p>
              {i < workflowStages.length - 1 && (
                <ChevronRight className="pointer-events-none absolute top-1/2 -right-3 hidden size-4 -translate-y-1/2 text-border-strong lg:block" />
              )}
            </li>
          ))}
        </ol>

        <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {stats.map((s) => (
            <div key={s.label} className="rounded-xl border border-border bg-surface p-4">
              <div className="flex items-baseline gap-2">
                <p className="font-display text-2xl font-semibold tabular-nums">{s.value}</p>
                <span className="rounded-md border border-border px-1.5 py-0.5 font-mono text-[9px] tracking-wide text-muted-foreground uppercase">
                  Sample
                </span>
              </div>
              <p className="mt-1 text-xs text-muted-foreground">{s.label}</p>
            </div>
          ))}
        </div>


        {/* Evidence sources */}
        <section id="evidence-sources" className="mt-16">
          <SectionHeading
            eyebrow="Stage 01"
            icon={Layers}
            title="Evidence Sources"
            body="Internal evidence you uploaded, plus external evidence PM Atlas discovered automatically."
          />

          <div className="mt-8 grid gap-6 lg:grid-cols-2">
            <div>
              <div className="flex items-center gap-2">
                <Upload className="size-4 text-muted-foreground" />
                <h3 className="text-xs font-medium tracking-widest text-muted-foreground uppercase">
                  Internal evidence
                </h3>
              </div>
              <ul className="mt-4 space-y-2">
                {internalSources.map((s) => (
                  <li key={s.id} className="rounded-xl border border-border bg-card p-4">
                    <div className="flex items-start gap-3">
                      <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-surface-2">
                        <s.icon className="size-4 text-muted-foreground" />
                      </span>
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="text-sm font-medium">{s.label}</p>
                          <span
                            className={`rounded-full border px-2 py-0.5 text-[10px] ${statusStyles[s.status]}`}
                          >
                            {s.status}
                          </span>
                        </div>
                        <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                          {s.description}
                        </p>
                        <p className="mt-2 flex flex-wrap items-center gap-2 font-mono text-[10px] text-muted-foreground">
                          <span>{s.formats}</span>
                          <span>·</span>
                          <span>{s.records}</span>
                        </p>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <div className="flex items-center gap-2">
                <Globe className="size-4 text-muted-foreground" />
                <h3 className="text-xs font-medium tracking-widest text-muted-foreground uppercase">
                  External evidence
                </h3>
              </div>
              <p className="mt-2 text-xs text-muted-foreground">
                Discovered automatically — no upload required.
              </p>
              <ul className="mt-4 space-y-2">
                {externalSources.map((s) => (
                  <li
                    key={s.label}
                    className="flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-3"
                  >
                    <s.icon className="size-4 shrink-0 text-muted-foreground" />
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium">{s.label}</p>
                      <p className="font-mono text-[10px] text-muted-foreground">{s.detail}</p>
                    </div>
                    <span
                      className={`inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] ${statusStyles[s.status]}`}
                    >
                      {s.status === "Collecting" ? (
                        <Loader2 className="size-3 animate-spin" />
                      ) : (
                        <Check className="size-3" />
                      )}
                      {s.status === "Collecting" ? "Collecting…" : s.status}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <div className="hairline mx-auto mt-16 h-px" />

        {/* Key findings */}
        <section id="key-findings" className="mt-16">
          <SectionHeading
            eyebrow="Stage 02"
            icon={Search}
            title="Key Findings"
            note="Sample output"
            body="Synthesized insights across all evidence sources. These are observations, not recommendations."
          />
          <ul className="mt-8 grid gap-3 md:grid-cols-2">
            {findings.map((f) => (
              <li key={f.id} className="rounded-xl border border-border bg-card p-5">
                <div className="flex items-center justify-between gap-3">
                  <span className="rounded-md border border-border px-2 py-0.5 text-[10px] text-muted-foreground">
                    {f.kind}
                  </span>
                  <span className="font-mono text-[10px] text-muted-foreground">{f.id}</span>
                </div>
                <p className="mt-3 text-sm font-medium">{f.title}</p>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{f.body}</p>
                <div className="mt-4 flex items-center gap-3">
                  <div className="h-1 flex-1 overflow-hidden rounded-full bg-muted">
                    <div
                      className="h-full rounded-full bg-accent"
                      style={{ width: `${f.confidence}%` }}
                    />
                  </div>
                  <span className="font-mono text-[10px] text-muted-foreground">
                    {f.confidence}% conf
                  </span>
                </div>
              </li>
            ))}
          </ul>
        </section>

        <div className="hairline mx-auto mt-16 h-px" />

        {/* Opportunities */}
        <section id="opportunities" className="mt-16">
          <SectionHeading
            eyebrow="Stage 03"
            icon={Lightbulb}
            title="Product Opportunities"
            note="Sample output"
            body="Actionable opportunities generated from the findings. Open one to see the full rationale and evidence trail."
          />
          <ul className="mt-8 space-y-3">
            {opportunities.map((o) => (
              <li key={o.id}>
                <button
                  type="button"
                  onClick={() => setSelected(o)}
                  className="w-full rounded-xl border border-border bg-card p-5 text-left transition-colors hover:border-border-strong"
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <p className="font-mono text-[10px] text-muted-foreground">{o.id}</p>
                      <p className="mt-0.5 text-base font-medium">{o.title}</p>
                    </div>
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="rounded-md border border-border px-2 py-0.5 text-[10px] text-muted-foreground">
                        {o.impact} impact
                      </span>
                      <span className="rounded-md border border-border px-2 py-0.5 text-[10px] text-muted-foreground">
                        ICE {o.ice.toFixed(1)}
                      </span>
                      <span className="rounded-md border border-border px-2 py-0.5 text-[10px] text-muted-foreground">
                        {o.status}
                      </span>
                    </div>
                  </div>
                  <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{o.outcome}</p>
                  <dl className="mt-4 grid gap-3 sm:grid-cols-3">
                    <div>
                      <dt className="text-[10px] tracking-widest text-muted-foreground uppercase">
                        Estimated impact
                      </dt>
                      <dd className="mt-0.5 text-xs">{o.estImpact}</dd>
                    </div>
                    <div>
                      <dt className="text-[10px] tracking-widest text-muted-foreground uppercase">
                        Estimated effort
                      </dt>
                      <dd className="mt-0.5 text-xs">{o.effort}</dd>
                    </div>
                    <div>
                      <dt className="text-[10px] tracking-widest text-muted-foreground uppercase">
                        Suggested experiment
                      </dt>
                      <dd className="mt-0.5 text-xs">{o.experimentShort}</dd>
                    </div>
                  </dl>
                  <div className="mt-4 flex items-center gap-3">
                    <div className="h-1 flex-1 overflow-hidden rounded-full bg-muted">
                      <div
                        className="h-full rounded-full bg-accent"
                        style={{ width: `${o.confidence}%` }}
                      />
                    </div>
                    <span className="font-mono text-[10px] text-muted-foreground">
                      {o.confidence}% conf
                    </span>
                    <span className="inline-flex items-center gap-1 text-[11px] font-medium text-accent">
                      View evidence <ArrowUpRight className="size-3" />
                    </span>
                  </div>
                </button>
              </li>
            ))}
          </ul>
        </section>

        <div className="hairline mx-auto mt-16 h-px" />

        {/* Strategy report */}
        <section id="strategy-report" className="mt-16">
          <SectionHeading
            eyebrow="Stage 04"
            icon={FileText}
            title="Strategy Report"
            note="Preview only"
            body="Generate polished, exportable artifacts for leadership and product teams."
          />
          <div className="mt-8 grid gap-3 sm:grid-cols-2">
            {artifacts.map((a) => (
              <div key={a.title} className="rounded-xl border border-border bg-card p-5">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-sm font-medium">{a.title}</p>
                    <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">{a.body}</p>
                  </div>
                  <FileText className="size-4 shrink-0 text-muted-foreground" />
                </div>
                <button
                  type="button"
                  className="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-border-strong px-3 py-1.5 text-xs font-medium transition-colors hover:bg-surface"
                >
                  <Download className="size-3.5" /> Generate (coming soon)
                </button>
              </div>
            ))}
          </div>

          <div className="mt-6 rounded-xl border border-border bg-card p-5">
            <div className="flex items-center gap-2">
              <Sparkle className="size-4 text-muted-foreground" />
              <h3 className="text-xs font-medium tracking-widest text-muted-foreground uppercase">
                Executive summary
              </h3>
              <span className="rounded-full border border-warning/40 px-2 py-0.5 font-mono text-[10px] tracking-wide text-muted-foreground uppercase">
                Sample output
              </span>
            </div>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              {company}'s strongest growth constraint is activation and monetization fit, not
              feature breadth. Onboarding friction and seat-based pricing account for the majority
              of negative sentiment, and your own funnel data confirms the drop-off. Shipping
              guided onboarding and a usage-based tier addresses the two highest-confidence
              findings.
            </p>
          </div>
        </section>
      </main>

      {selected && (
        <OpportunityDrawer opportunity={selected} onClose={() => setSelected(null)} />
      )}
    </div>
  );
}
